### ISSUE TITLE
Error running cronjob

### ISSUE THREAD

**Issue by MaDTaZ** [taylorbourne/xteve_lazystream#59]
It did run this morning and has games from yesterday so not sure what is up. Seem to be only the nhl mlb is working fine.

2021/09/26 16:57:44 [cronjob.sh] Creating .m3u & .xml for XMLTV...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/stream.rs:305:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tarkah** [comment]
I just pushed out a fix for this error in `lazystream`.

If you restart your container, it should pull that latest release and work.

**Comment by MaDTaZ** [comment]
restarted my container but still getting that message.  How can I tell if it pulls every thing properly?

**Comment by tarkah** [comment]
You should be able to see some log lines related to it with `docker log`

When's the last time you updated the docker image? The check for updated lazy stream was only added a few tags back.

**Comment by MaDTaZ** [comment]
It says that I am running the latest version look to be 1.20. have my setting to this 'taylorbourne/xteve_lazystream:latest

**Comment by tarkah** [comment]
Here's my docker logs, it appears to have updated successfully and run. You can see it logs the errors, but the files still get written to in the latest version:

```
[cont-init.d] 60-update-lazystream: executing...           [update-lazystream] checking for update                    [update-lazystream] installed version: v1.11.6             [update-lazystream] remote version: v1.11.7                [update-lazystream] newer version available, downloading...Are you sure you want to trust it? (y/N): Connecting to github.com (192.30.255.113:443)                               Connecting to github-releases.githubusercontent.com (185.199.109.154:443)                                             saving to 'lazystream.tar.gz'                              lazystream.tar.gz    100% |********************************| 4517k  0:00:00 ETA                                       'lazystream.tar.gz' saved                                  [update-lazystream] lazystream successfully updated to v1.11.7                                                        [cont-init.d] 60-update-lazystream: exited 0.              [cont-init.d] 70-chown-files: executing...                 [cont-init.d] 70-chown-files: exited 0.                    [cont-init.d] 99-firstrun: executing...                    2021/09/26 17:56:14 [cronjob.sh] Running scripts...        2021/09/26 17:56:14 [cronjob.sh] Running Lazystream (NHL 720p60 via akc)...                                           2021/09/26 17:56:14 [cronjob.sh] Creating .m3u & .xml for XMLTV...                                                                                                               ERROR: Failed to resolve stream for game 2021010008                                                                   Caused by: missing field `editorial` at line 4 column 1                                                               ERROR: Failed to resolve stream for game 2021010009                                                                   Caused by: missing field `editorial` at line 4 column 1    2021/09/26 17:56:14 [cronjob.sh] Playlist saved to: "/playlists/lazystream/lazystream-nhl.m3u"                        2021/09/26 17:56:14 [cronjob.sh] Xmltv file saved to: "/playlists/lazystream/lazystream-nhl.xml"
```

**Comment by MaDTaZ** [comment]
Ya it is saying I have installed version: v1.11.6

**Comment by tarkah** [comment]
Hmm, should be updating to 1.11.7. You can manually edit the Dockerfile in this repo to have it download 1.11.7 and rebuild the image manually.

**Comment by MaDTaZ** [comment]
I still leaning docker so not sure how to do that.

**Comment by fkick** [comment]
Just restarted my own docker and am getting errors on the update to 1.11.7:

```
[update-lazystream] checking for update
[update-lazystream] installed version: v1.11.6

[update-lazystream] remote version: v1.11.7

[update-lazystream] newer version available, downloading...

Are you sure you want to trust it? (y/N): Connecting to github.com (140.82.112.4:443)
wget: server returned error: HTTP/1.1 404 Not Found

tar: can't open 'lazystream.tar.gz': No such file or directory
mv: cannot stat '././lazystream': No such file or directory
rm: cannot remove 'lazystream.tar.gz': No such file or directory
```

**Comment by MaDTaZ** [comment]
I finally got mine updated I just went back to 1.14 and then went to latest again and every thing is fixed on my end I am closing the ticket 

Thanks @tarkah
